---
name: Check ğŸ› 

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main
      - test-docs-publishing-workflow
  workflow_dispatch:

# Required by publish-docs, despite REPO_GITHUB_TOKEN being used.
# permissions:
#   contents: read
#   pages: write
#   id-token: write

jobs:
  # audit:
  #   name: Audit Dependencies ğŸ•µï¸â€â™‚ï¸
  #   uses: insightsengineering/r.pkg.template/.github/workflows/audit.yaml@main
  r-cmd:
    name: R CMD Check ğŸ§¬
    uses: insightsengineering/r.pkg.template/.github/workflows/build-check-install.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
    with:
      deps-installation-method: setup-r-dependencies
      additional-env-vars: |
        _R_CHECK_CRAN_INCOMING_REMOTE_=false
      additional-r-cmd-check-params: --as-cran
      enforce-note-blocklist: true
      note-blocklist: |
        checking dependencies in R code .* NOTE
        checking R code for possible problems .* NOTE
        checking examples .* NOTE
        checking Rd line widths .* NOTE
        checking S3 generic/method consistency .* NOTE
        checking Rd .usage sections .* NOTE
        checking for unstated dependencies in vignettes .* NOTE
        checking top-level files .* NOTE
  r-cmd-non-cran:
    name: R CMD Check (non-CRAN) ğŸ§¬
    uses: insightsengineering/r.pkg.template/.github/workflows/build-check-install.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
    with:
      deps-installation-method: setup-r-dependencies
      additional-env-vars: |
        NOT_CRAN=true
      enforce-note-blocklist: true
      concurrency-group: non-cran
      unit-test-report-directory: unit-test-report-non-cran
      note-blocklist: |
        checking dependencies in R code .* NOTE
        checking R code for possible problems .* NOTE
        checking examples .* NOTE
        checking Rd line widths .* NOTE
        checking S3 generic/method consistency .* NOTE
        checking Rd .usage sections .* NOTE
        checking for unstated dependencies in vignettes .* NOTE
        checking top-level files .* NOTE
  coverage:
    name: Coverage ğŸ“”
    uses: insightsengineering/r.pkg.template/.github/workflows/test-coverage.yaml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
    with:
      deps-installation-method: setup-r-dependencies
      additional-env-vars: |
        NOT_CRAN=true
  # linter:
  #   if: github.event_name != 'push'
  #   name: SuperLinter ğŸ¦¸â€â™€ï¸
  #   uses: insightsengineering/r.pkg.template/.github/workflows/linter.yaml@main
  # roxygen:
  #   name: Roxygen ğŸ…¾
  #   uses: insightsengineering/r.pkg.template/.github/workflows/roxygen.yaml@main
  #   secrets:
  #     REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
  #   with:
  #     deps-installation-method: setup-r-dependencies
  #     auto-update: true
  # gitleaks:
  #   name: gitleaks ğŸ’§
  #   uses: insightsengineering/r.pkg.template/.github/workflows/gitleaks.yaml@main
  # spelling:
  #   name: Spell Check ğŸ†
  #   uses: insightsengineering/r.pkg.template/.github/workflows/spelling.yaml@main
  #   secrets:
  #     REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
  # links:
  #   if: github.event_name != 'push'
  #   name: Check URLs ğŸŒ
  #   uses: insightsengineering/r.pkg.template/.github/workflows/links.yaml@main
  # vbump:
  #   name: Version Bump ğŸ¤œğŸ¤›
  #   if: github.event_name == 'push'
  #   uses: insightsengineering/r.pkg.template/.github/workflows/version-bump.yaml@main
  #   secrets:
  #     REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
  # version:
  #   name: Version Check ğŸ
  #   uses: insightsengineering/r.pkg.template/.github/workflows/version.yaml@main
  # licenses:
  #   name: License Check ğŸƒ
  #   uses: insightsengineering/r.pkg.template/.github/workflows/licenses.yaml@main
  # style:
  #   if: github.event_name != 'push'
  #   name: Style Check ğŸ‘—
  #   uses: insightsengineering/r.pkg.template/.github/workflows/style.yaml@main
  #   with:
  #     auto-update: true
  #   secrets:
  #     REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
  # grammar:
  #   if: github.event_name != 'push'
  #   name: Grammar Check ğŸ”¤
  #   uses: insightsengineering/r.pkg.template/.github/workflows/grammar.yaml@main

  # TODO this is probably not necessary - we can have just one job after pkgdown.(?)
  # but if pkgdown completes first, then updates to coverage and unit-test reports will not be reflected in GH Pages.
  publish-docs:
    needs: [coverage, r-cmd-non-cran, r-cmd]
    name: Publish docs
    uses: insightsengineering/r.pkg.template/.github/workflows/publish-docs.yaml@feat/add-workflow-for-publishing-to-gh-pages
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
